name: Update NSE Stocks to Google Sheet

on:
  schedule:
    - cron: '45 14 * * 1-5'
  workflow_dispatch:

# GitHub Actions को फाइल कमिट करने की अनुमति
permissions:
  contents: write

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install gspread oauth2client pandas requests

      - name: Run Python Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python update_sheet.py

      - name: Commit and push stocks.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stocks.json
          git commit -m "Auto-update stocks.json data [skip ci]" || exit 0
          git push
